---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-cluster-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  path: ./kubernetes/apps/cert-manager/cluster-issuers/app
  prune: true
  wait: true
  interval: 1h
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
