---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: applejack
spec:
  interval: 30m
  url: ssh://git@github.com/fobiat/AppleJackRP-sandbox.git
  ref:
    branch: main
  secretRef:
    name: applejack-git-auth
