---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1ln5mrgxe4un2crexzkuztp0df6rmxjczkumlejzqktzrqjt3svxsr4eszk
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1ln5mrgxe4un2crexzkuztp0df6rmxjczkumlejzqktzrqjt3svxsr4eszk
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1ln5mrgxe4un2crexzkuztp0df6rmxjczkumlejzqktzrqjt3svxsr4eszk
