---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-check-umami
  labels:
    gatus.io/enabled: "true"
data:
  umami.yaml: |
    endpoints:
      - name: umami
        group: apps
        url: "https://umami.lab.fobiat.dev/api/heartbeat"
        interval: 1m
        conditions:
          - "[STATUS] == 200"
