apiVersion: v1
kind: Secret
metadata:
    name: umami-app
type: Opaque
stringData:
    APP_SECRET: ENC[AES256_GCM,data:EU2Ssg6ix9ZXV4c1bJFad8Rimi7dS32XmQMVkh+K24PhrisU5O07Zzw4oOnL8+I2udP34Nz2vmI9QSBIbnqpPDw=,iv:KJU0DPXuxY1oYu3IQUIDbpIIWOMc3oG4eFikDSnu9eM=,tag:85EMsNE+NETQfYWIu4p6Fw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbklHclFMbHJ5N3Z3dHBq
            dldaMVFqdm96b1lER3FRekkva2N5ZWlCRTE0CnN0aGV2L1grTWM5bUdnc2ZvQjZC
            amFZS1hzVEdlU0JCQTA5bXZiODJZM1kKLS0tIHJDWEdBSjQ0akNqTmJYNXY5WUpF
            cmVBcHZ5aVVOQnFKdTFKUVlNRzlhbXcKdbFgD1Kx3taIv4Ki9Pb9raNMJkiIcyT9
            boBpk56OB/Fw+hxTLeR50cSeKJk12lNNly95JUsOeSOABkEJs8LVsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T02:50:03Z"
    mac: ENC[AES256_GCM,data:2LkPMskpxJbkgn9F0tMQDAbtxpaqoJ0kuUOD4krSZ3JBHgVR1QAQJZBS2VMLi0A6BppC204/kwLZ4jSPRhgc7AT/NZ31fprRkAukYC+II5U3YizL5BECPxhKgJgZnfOm+Dxxg/NHANJ3pJV9/Xbhd7atYcJR+HYK6xi6qjhJLug=,iv:5tVHz/e6qqPOOMbkRkq4kNZ5bgk0H2l3Gd4TEw2e9ho=,tag:KaGDqTkw7/OAVlGBVMWhGg==,type:str]
    version: 3.13.3
