apiVersion: v1
kind: Secret
metadata:
    name: umami-app
type: Opaque
data:
    APP_SECRET: ENC[AES256_GCM,data:70lEhtxA19L4OedMt0WU2TwW9MVehhVQ+61TLaTpAfJ5gXQyn9ZoGIUGjdcmMpBMSrgRM1T2yxDDSQ6qdP/cZ6cbbrl5yHiSY4ajBTAmchoCm4paSO7G3Q==,iv:9+pLXN2KRvBof57aC4oAVI5RE87AT9i8tRbnh0yN/Go=,tag:tfvJJZa8ZsO5rdblxyEPSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbklHclFMbHJ5N3Z3dHBq
            dldaMVFqdm96b1lER3FRekkva2N5ZWlCRTE0CnN0aGV2L1grTWM5bUdnc2ZvQjZC
            amFZS1hzVEdlU0JCQTA5bXZiODJZM1kKLS0tIHJDWEdBSjQ0akNqTmJYNXY5WUpF
            cmVBcHZ5aVVOQnFKdTFKUVlNRzlhbXcKdbFgD1Kx3taIv4Ki9Pb9raNMJkiIcyT9
            boBpk56OB/Fw+hxTLeR50cSeKJk12lNNly95JUsOeSOABkEJs8LVsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T04:22:57Z"
    mac: ENC[AES256_GCM,data:HP6IDWIKsRUTEdqIOoTcxi0JtYBKVZOzsI+lBuZW/pA76D1jfXkzMxk5KhqnzSf/RMJDco7QGf4lBAv7uJpr7m14FJ5cBuq32IfSvnFC1CD+2cSHGk2xV30/OU+sRvggGE9c75SQArcgucYcs2a9sLKfx+wdpOKM9iw21gvBDBU=,iv:h2awO7b5Sy/RlFfWaAPaFyn8W4ytPTKz/qIUl5lLYE4=,tag:MbZouuqkCw5lDyvM5MJJwg==,type:str]
    version: 3.13.3
