apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:rkNxla0DHc8yRPSIfblO6bVRh8GwpEYvg+4+W/W5GwqQ3w4ywdTIy/Qb08xCrVDfPM8AmkjngN/l3QXCNylAQlIgbzKraSybYS6N0JreTjsmev3xfWJI8v4FfTxlUolmZDsd0rDrqM7V53tIymCnGOGRcmngrP9zEA6FKpvZcYlpOHzjxjcReWTN6IO9hHpD7rYsO8T55q5OrjKJv7AN/p0sEskve9l5I7tvzpdytw==,iv:hfkz3S8RYwQ8n5BPnfi+AsdMCm0/CdAbUYGcBroLkUA=,tag:IUKcewC6mf1wgYV23eDwUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUmk0VE9uNmFuSmpUOFJS
            MjE1MjlhYTQ2bUE3NlZ1NnhuclBwdy80cXpJCi9ybGZTWm5rRTgzVzZYVE9Hd1V3
            SUlLQWx6RE9LMnhzTzFaQjI0Vk5MNzQKLS0tIGhsdEI2UmJGajdDQnZXTlBIV1dB
            R3VvTW9RN3dST3VwQ3dKYjFJaGI4ZUkKaG3VOzRJ542MaVikseQ5yuAyqVea5vT2
            0mqs9Ni0eQJz8pXkTnG+ypPc7/W5TSBUr4ytObxGNtRBLLYTH8fLGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T19:07:35Z"
    mac: ENC[AES256_GCM,data:v/742/gKe5Tt8yospcuEuuZigW36Qv1S2BKTzVn9/mm/AcS3UoHg1HBfoLk53myqaL60m2K++WHqNbMCH9TK2cUkg2Hnb6frI1FLtAFpFQgxlg14Eexp8kNtkmWve3au774YRFfOXTcjTLcaanxzwUq9wLNJT8Ml9JJo6IYf8k8=,iv:0IVaSAhcuY94oxhk0vkWO9XCDtat1AiOS5BzZ5ZrKDg=,tag:Ko1HPJaCiyCu9SuIQjrcNg==,type:str]
    version: 3.13.3
