---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cairn
spec:
  interval: 30m
  url: ssh://git@github.com/fobiat/cairn.git
  ref:
    branch: main
  secretRef:
    name: cairn-git-auth
