---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace/ks.yaml
  - ./registry-auth/ks.yaml
  - ./automation/ks.yaml
  - ./database/ks.yaml
  - ./bridge/ks.yaml
  - ./app/ks.yaml
