apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:iLCmkIKdNtLAwDYfgS6i5pmhE72JTFNhzDoTCTBuN+D6ZYWTUBquRReoHPT+n7KaQEBersdojbBA85o5YkD8pFzyvhDacO2VqesTi1RTCm8VhV/O6am4rpZvfgtctjYPHN0GMhDSonEyOK0mK9ImBafS5TB1A+9CART1w855QqzkbcwRx+WqXTYgkpH6fRh/p0CKShWdOTzy7nJQs48FeNeoHBldMFEHlEmCmHm/N3Qqz1PDMCLjGLauwMwQCHPE1wYSi5x3Mwii5vXgIjVx65rAAEXudMyaFvarXvBE6nXdyGCbZDkRCXhUiRYeYQa2gIHoBdMWMUh7yapWfupaxRhEeGplVMox,iv:S1uXS8iQWngTe0xjPHZHBDWN2BvuMYmm5GOi6tBZVXg=,tag:65hRXCu8soHj98v7fwR76Q==,type:str]
kind: Secret
metadata:
    name: applejackrp-ghcr-pull-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZGUvRTZnZit4dmZ1TXgr
            OWJXNXV3Q3g4TmJaUElCODFyZU8vc002MFUwCkZwR3JteEgyU1VRNC9EWFMxaHQr
            SCtqMzdYU04vamhaNDdYTEsvbkUvWjgKLS0tIGU2QllyWkwzKzkrOUtMeWJiYm1Q
            VFRoMUMvdElwU0trTFZQS1B5aStKRjQKu0q/+AeEpDTBtmADbhQKON3LMKCYRnjO
            tY1+1tF0LDbTNoAPc2zpM2IUFHGWPL+wBO1JFwcMO7uyqjw9LwTmOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T17:44:39Z"
    mac: ENC[AES256_GCM,data:1TquNfQ7/p1nPUUMXGLKgGrRiNIYxUihZyud5wxN6nQVUCRHSTQllAvpjExqettVO2hCR3xbZiBMrvrETK93ySckTj/qIlwdJh1unsN8vEedVkvKGlkpEkdcUPKa78uyjOYRz0tMyCcz7w8adcTAIpKMsSEVdbxUhcbuBMmiGQ4=,iv:Oe9jjg58YPV0S1XBBFbFX8XxHnBW1dq9JLtSD91ZxL8=,tag:6Ud5C/jgf84xXcn1PYBO0Q==,type:str]
    version: 3.13.3
