apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:VZyz1Kl9wD1UkUXyQi8d+A8641yz526j04Q2YR6sA4wiLhuU0sCUhTBZDG8h8zqo7SXVxA3dmm2na6dmRVFJJ/T9v+LAt6vejs5Ny1Ujrwe8Rr1zpnHqkRKpG0naekL3apcY+/NJgF/WId8EHaVHdJ7Jt84qcOEEoo075qK0JLHhI7Er2ZzKsTShQunKqkh+x9RASnRar+Wrdnd/of2AZMOmZrBQQfcRsyw0qzr7i70wnFuLM1p8aMZKIEIU3mf7id/FNZLgk7FhZ71GSgnccLKyt9psD533N3Zmray1nUgjLJeXVsyUtHooN6tq78m3ZdW52ZuPyTVxNMKiNzhUyxB35DgFykqDHdK+4pDOifiQ5cKciu7L8rjHJTVB7DOhZXFt1IirZA/jZGlhn7JXiLQB+FQqtDnweCU0NPZH0+Y8/gRlDS4t8wjYArJZTrWmUbiczlSiYbxVGUr+QvAAXPHEkWIqZQFyy7aQmdWUw8xNccI281MWGVrPbnCWYqbaW7fmeDzKM42cV7OIRUKVtOe7QapG1Ry76sDdQUCdiagOwORd/AvQbR/BhNklY51O,iv:DMBsbRkrxEMre5wC/bRNIatEDi+ogav+oU3SKQzuArI=,tag:LYlMg29j5F6JZ6Dr35/63Q==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMGMyZWlzNldLS2ZPTTBw
            NnBKWFo1S29MdmRwUzFGUmF0OUJtZ2gyTEVRCmRuTXVGSVh1RXhSajNjVWlqVjhM
            aVhyZHRRT2lLSG5uUVJXRGx6UHNZY2MKLS0tIE9OaFZ4SkY4YW1uU3ZKeGtGS1hY
            M3QxUkFPOCs5OEMrQWdHUTB1ZXZ3NFEKblAmviW35bwsvTTmg7/2qyvJ79ieQGqA
            4nY4xKKlB0DtMTwYtUUh9MpK8BOOP6VfwCNJq2T0VWxdQrmS4iqdjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T16:40:18Z"
    mac: ENC[AES256_GCM,data:uvG/7/aWGT/GClmljzfBkNrkEVrgb3rC7zHNyeLBSYYs0ZBnz8nIrNwMvfKPRe+ce8EiTCXDA3SfAfC9mJPy6L5Aj11JyrbUkT9xQAZwBo3s+drpb5TwPcOW8LFx7T1RAhD3On4kei0hRsIeH/tCdSsIa3qKOTmL8dkCUlsnDvA=,iv:W0x1G3tsEknBx112fH5MLbP85ZuO22s7y1w3kg3AAio=,tag:5pM8hgRW+KOtrYfCVkUKRA==,type:str]
    version: 3.13.3
