apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:rmh/edbnifB+0WJuqM+MV4h3CTlO6ikpzDLxYhSnZA9vGaolUwgHBkCUYrL5r8ijHXfsi5zG6ITISEEgIK1cqzlKTyyYXGWKJ3ORHDuWixvusxMuhyB7U4b2/mktw/WiPb7tJMtXgQ/AQzFLDL4bhgwdKlRtEh0sv0RnwhZGEwo5SpuKNCHoQIdAYaB9BcSlIn7q03vV6Uspt0lpeaIZECcf0A+5OVy1Q57T6sTCfP1rJexvamGXX7ZeVdZDfRffqqYJn6x/COJQd7Xz0mYey585aHKf/Ni6y8IDurJcGARlZwqYHB2EtTPrMqRybCctAZ4oqOGbZsUSFvbPpQlMEh3rFz7WmfrI,iv:fV7AA+72ZS8n3EhDcO1GRvXHCR/6v/q+LeEPJD1a+8Q=,tag:XPMWbpOELmJxruDT0MasoA==,type:str]
kind: Secret
metadata:
    name: applejackrp-ghcr-pull-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUEZGMDl5bFZTemEwTTZm
            Vkh3MVV1ejB1YWo3Q0RXS0xNRFF3MjZ0b3k4CkxlVGZibGJpOGxOWFNFbkNqVUJv
            Q3JuN1VTZDJ3NHo3WVlrdnJuWkRETmcKLS0tIGVqRmtpbm5JdE1qS3NidkRkOVUr
            OEdUbUR6SzEyazg4VGZrbFFESEVqT00K2YTfJjeJGE/eAvMAhCZbUPcYmd1i39AD
            KJIhLCWVhQZhbm4AP7q2f37cELqHNj6x1itc6d2eiE+IN80hZ9hbWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T17:26:41Z"
    mac: ENC[AES256_GCM,data:5Wnv038S7afkOY/0Qx2qdlgzcEQbeBfGQSquYc5XmQfk5Qf2VBB6BecTI6fbkzDxkHaes6Wtv5Xu3WsTs1BRAr7xxm+oO3nsp3/0ZFYTo84P/afa+TvskMH6RsUtMsgVMG7hyQ8zdQlMhgzZkF7+jAlrH1+r9KWGXeVi9O2ACEY=,iv:Cw2Oyb54TgdLwoaUA8fsj+h0xI8Q82vmlArzfMEa1T4=,tag:65nPnkD05sNXIDXlH6zEyQ==,type:str]
    version: 3.13.3
