apiVersion: v1
data:
    token: ENC[AES256_GCM,data:zGSGoQ6lWpT9iFETQqGJ6YfFiiZz2mjnTSqACoa2FQ3sUM8KePThsqynHhM=,iv:EHAdNVa9ZFWrTTx3vo6E1b3kcX2kwQeG5iYes2liWV0=,tag:GHCvl6AYVdhP7GcsDeLxNA==,type:str]
kind: Secret
metadata:
    name: applejackrp-gslt
    namespace: applejackrp
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuanFZYlhmLzdsd3VWb1BV
            NDhCL05YcFowMG8wdXJNS1RCK0JJRkFyMlNBCmIyK1JjYnlJWnVHRk13VGl2NExV
            enhYd1RYQUcrc01HRnlqZGxRV3BMN2sKLS0tIG5Yc001L1lGZVM5NzJhTVd2TlFF
            QmxVb0lZRmw2alhxeW5rTEh5cGZuamMK6Ifwvd69elH2mf0iYdhhaF7PZUNNYrRS
            rsxZa8ssQGSoHUcgf2y0FzfdkmiwDK7pwyBSnSUue9b5WpYrntoK1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T17:01:11Z"
    mac: ENC[AES256_GCM,data:oHSz8TwfUT2qGvxllak1dDcxZLtr3Al9WFQHrV5OG6eRH4l06D5jz4mD18bqT4KRqCPctXfCB0eh1ThKJqqP/NpsihjZ7LOE8wEBOPzHif7XREv/q9+wudx1ojJkvfQHw40CXeqm09i4Hq84Khi8bMsiV3gaPPNvCVXDH3EQj1k=,iv:VgWMP3sI66LK/WM/9SZuw8t2UgJqeMHVPFWrc8tWv00=,tag:9VaOSdkZMH80zzAP5YL30A==,type:str]
    version: 3.13.3
