---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: umami-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-minimal-trixie
  bootstrap:
    initdb:
      database: umami
      owner: umami
  storage:
    size: 10Gi
    storageClass: local-path
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 512Mi
