---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-cloudflared
  namespace: flux-system
spec:
  targetNamespace: network
  dependsOn:
    - name: reloader
  commonMetadata:
    labels:
      app.kubernetes.io/name: network-cloudflared
  path: ./kubernetes/apps/network/cloudflared/app
  prune: true
  wait: true
  interval: 1h
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
