apiVersion: v1
kind: Secret
metadata:
    name: grafana-restic
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:RVD+uleZOrSt0F8C/8xKm7g=,iv:RQ1vSeXD9yh3de9PO6YaRv3T894MlUQr1pG1yFMfisE=,tag:+oCLlj2eWTpA45kodRyZuA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:wd3CKGbFBvYqR8Ncar3q3LXAiCL/oOGG+KdpGxfQYvjSuIaV8sp/6x5sjDg=,iv:1gJSPSww8/qJci0MOKJJL5dpcVJeFE150xkMkNxzjbU=,tag:BQTdAqYvzT2nRrJtCrGLGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdE9JWGZmL1QxaWwrMzZh
            Z0ZtWEpzWi8rTXorV2MxOEJxQzlpWFJHSEcwCmYrcWUwb0ZtZ21xdjdCUVI0K1lS
            V0dHejM1YTBGMDFETGpwTTNjUUFySmcKLS0tIExuTzZUV2U2K01reklIRE05UFdq
            RmIwWDNPRVZRdzFlNFlsZllTeXFMa28KM3nVYLhSflp7RzRr3BGajMPW/bYTOGZ/
            +5KLRbkCoOwyZiaZ32o48nBJjh0La8mailySidyNpN93NUqBNW/KOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T14:24:36Z"
    mac: ENC[AES256_GCM,data:xAu+IoJjbpex/N6FAkIbRiCzF/m9vV6Q+HcOCJUAiUvnQDGCGgIT55U14XUPYJVcA9xCQAeEEpM8FHc5PsjXYs5X5nDWY00s3845ZDd74jwXm2oC80FFXEdqAkZANZognbfSkyi+R3iW/+ewhxee5vUOfiY94uaDxaKa/y5qz48=,iv:08Etl94O18o3tlimebLzf00STlkgwR4KEMZZ0Vi3nWI=,tag:tvh6j3/p5wBC2jlQBExQww==,type:str]
    version: 3.13.3
