apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:GBkra9Q=,iv:2orW8wqOCF1dHXoZG7U0wvGdgdFgSomvEDMF0M0KVek=,tag:C4b4c+ErM4PI37EEknfiWQ==,type:str]
    admin-password: ENC[AES256_GCM,data:ebsaVFxPFWNj3VK33CenMfnQ8PZ5d+UA,iv:fOGHH7/yNx+d4zzjF5WD65PTxwlNx2HlThtBr9fmBtM=,tag:RywYMTZDn2oUOB5ULm1/Lw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcG53V1dUczg3UzV4Zldl
            MWY5Qmx6aHB5elFBeGNXYWhRNEx6SW5XQVE0Cm5WRHRCbFlPWGs3R2JxcExUNjlL
            WEFrdzVScmovV1dhSWZBTTFBOWtNZkUKLS0tIFlHelcyRXBGTG5JejhhWHAxTXdZ
            QUZnakJweEpZOXNDRi82SzN6ZFJuYzgK+K7LlT22lZJZLj+CZzRjN+H3bcoWsN36
            hxFuiW8nmyK0J1jRb1k3T2Bnx7sU0QFudq2pyH76stEJA8Rn3LfTKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T00:16:13Z"
    mac: ENC[AES256_GCM,data:g1GbqrizSWvRCO4W3SpBUd4bQ+RVWkgDRihVUrD4Zy1WXdy4MKbXp7EFcGDDo7kD6Nnd4hk8ZXhynkQIqCWKhcT/Lyt7YyOFjQuX1mbVKcz5GXpRH6CI0ptF397ZK77GhgeqdzpXvyQj0e6ywsLzCvCwZH4onkED7LiEYvlQeYQ=,iv:Qi1k95Q4/4jPWTRuiJi9jL6JjhjFSRJGPNHYcJFmlK0=,tag:G3EorkqqgE/CKcs19ZJ0Ww==,type:str]
    version: 3.13.3
