---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/namespace-privileged
resources:
  - ./grafana-admin-credentials.sops.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./gatus-check.yaml
  - ./prometheusrule-node.yaml
  - ./volsync-repo-pvc.yaml
  - ./grafana-restic-secret.sops.yaml
  - ./replicationsource-grafana.yaml
  - ./alertmanager-discord-webhook.sops.yaml
