apiVersion: v1
kind: Secret
metadata:
    name: gatus-restic
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:wiYASamQulqlmKNM8ciS,iv:jNg1RXe4sTLk+GOfBqg5mTha+qAUMWM7GaW3HQL/rj4=,tag:C9yto82SLmjPcMrshQMbig==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:HUxKxmHKFj39WwsjQwebYjoTlIs0ynE/EoORP4XPD7JxfcIfmf/iO5BMeRJe8r0RbC4qT7Qy7TpeVzlpGAqjwQ==,iv:lAZuKp960dcyc0XiabAbK8T+hgVWZlElx/J4y9FCJik=,tag:6BpjaEYTAG0m0/cSEqN5+g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:oOmtoDfLO5DcNAjmi9Ks58EMXRachXO1FfGWgOLhi2s=,iv:IZuCYMsdgs5PAs9Hd9Vy2niudDbQUV/7wUWTShZu8+0=,tag:aHqx05BxsL2xSFtGEq8zLg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IZVK3h3uoSo5LLvLn9qLFgpqOGmMiqpAs0Bx6m7zQe1glLKEFWOyIVIQpuSnR5OOlBajuaPPz4MeS8S5AcchhA==,iv:d2Ajzf5sIprNh79dR8cXAvfulB6Pwd808553WSgryTE=,tag:hK2cnEnAOPX+m4SvaRyI/A==,type:str]
    AWS_S3_ENDPOINT: ENC[AES256_GCM,data:FFXrYcFNArQykxC34z+5xCSZkqYxV0UGOEv6DCpT3E5iIG95Eo9RZt01G6UrZ91G6LgFHPpoBd+BBgsvxwtqBbo=,iv:PaLz68hJzM+8SdhokEZylELhcjdbFplc/yDGh40l9ac=,tag:KAC18AHmnDhoqk6Iwg+0vg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4K09ZaTRNRzNBbHp0ZnZ4
            dHp0eVBHVVZRNzdXT0pnWWxpVGpoUmxkT3hnCkNEYVNMaW5FRkl4encyenRqMzJQ
            OG0xNmFSeElyam9XblFqTXR2cDJOQlEKLS0tIHc1RFhnazRiRW5oRUM1ZUxLdHJX
            amFjelBFTUdqallZbUpRZlZYMXdLd3cKhrIn5jClhJRQO5G/HhCXJJKkX9mmt9MK
            0iehkSFxYzDpPGswdRuA5znHc1YulNPYQ70szGPI2NavgchUicX4wQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T11:03:39Z"
    mac: ENC[AES256_GCM,data:QyPA8UGIHqHFUaHBs/yvZBjGhAu1c+XIJixraZgrs5i4I+fxCRyKy54a8jUVEV//jB/cWhbAiYwNqzgtR8NkaGBy9sv7ZJwBBTQIkSMGDyEISq9hEQLneFx73aETkUgjR0xsaCLY/QjqDf1MO23/jGvduSCYrkjoDrJwaWi4U9E=,iv:uqihx3SfFDxKo26QG4B6V5il2XuIokTG4a/uEcifYN4=,tag:tCPfUUKPEf03lWDl6k/XzA==,type:str]
    version: 3.13.3
