apiVersion: v1
kind: Secret
metadata:
    name: gatus-restic
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:wiYASamQulqlmKNM8ciS,iv:jNg1RXe4sTLk+GOfBqg5mTha+qAUMWM7GaW3HQL/rj4=,tag:C9yto82SLmjPcMrshQMbig==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:HUxKxmHKFj39WwsjQwebYjoTlIs0ynE/EoORP4XPD7JxfcIfmf/iO5BMeRJe8r0RbC4qT7Qy7TpeVzlpGAqjwQ==,iv:lAZuKp960dcyc0XiabAbK8T+hgVWZlElx/J4y9FCJik=,tag:6BpjaEYTAG0m0/cSEqN5+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4K09ZaTRNRzNBbHp0ZnZ4
            dHp0eVBHVVZRNzdXT0pnWWxpVGpoUmxkT3hnCkNEYVNMaW5FRkl4encyenRqMzJQ
            OG0xNmFSeElyam9XblFqTXR2cDJOQlEKLS0tIHc1RFhnazRiRW5oRUM1ZUxLdHJX
            amFjelBFTUdqallZbUpRZlZYMXdLd3cKhrIn5jClhJRQO5G/HhCXJJKkX9mmt9MK
            0iehkSFxYzDpPGswdRuA5znHc1YulNPYQ70szGPI2NavgchUicX4wQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T13:29:20Z"
    mac: ENC[AES256_GCM,data:uQV9AMMGkucP1ypKQPlUn6Kxy6RDpSTjhOyvHSdMmGamK6ZJL+uvnHgWeU0eAt6LZ9c9ZDuSEhl6UPhyoZC6K9A0btZzK+DF9LLtoG7yCeYZVt587M4UmYcWsUDk+jvu2U+s6ilRLb+tTmtTouc1MEl6pNt1viOBKdQk6QuXJuY=,iv:8lzHh0cR1e2e3A2Y33JgUAXPrub3/X+sbao5+qfpaJg=,tag:fniZb99iGLPjZsQ7mnB2wA==,type:str]
    version: 3.13.3
