---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/London"
  KUBE_VIP_ADDR: "10.10.10.254"
  METALLB_LB_RANGE: "10.10.10.200-10.10.10.210"
  METALLB_K8S_GATEWAY_ADDR: "10.10.10.200"
  METALLB_INGRESS_ADDR: "10.10.10.201"
