apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:hFFecR60s/hp1h4VF+yW+IOIf1Wna1i4m/SXwk3Y/7PIc6BOfT2ZPSN6djLNlBLAZHEiEv+6OwCghk8NEQ1BSbWftFHdq3HfVmN1JAgtK7ig7DmtLHWE8FNpt9yXXWPy8Hsj+fES7DNf+XJ7ifyVhWT4gxL69gSr931LofE8E5n/TbTNDPKch/DFhRXb4Xc8ug1vxg3tqeJ7YD0kxwyXuZxnxx7iAHMM5hoQHJoyx1Eugoy3L5jD66VDbfsZ+Cj6wHmRmOgzkzLf5mezn0E/nvIf9AbGbrHGDq4emeCyKsIyBfXS,iv:R7aexEV9xMe9On8VJsFAiTlVhSuSuYfKK1Pf0HP1WBk=,tag:u/NhOIesfhwlzlk/zJItXg==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQmZYOWVpUFNiNXovd1Ny
            RFBRS0Z0Q2FHeFBvYWZCcmJkRHpqb0Uxd0dFCnFjRnJHYUFSbUpGZzk4Y1liZVpt
            Y2ozSVo5SStxbStDbFR0VjBGaWtnblEKLS0tIHhKcVlLYzZsemtKWXYzUkR2bFE4
            VVczNjJicm1GekVoaU1kOThNVXNFbkkK27hPj83TkujfxKDjxFJTPLfYnbH1lY9Q
            tl3HakTknSKfeLmhBpA3g6FrHqaXXE7sgoME4xQWWiV3oKt0hwYCeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T23:44:41Z"
    mac: ENC[AES256_GCM,data:OX7yJ93u7cvBQ7H565VRMH8LJEBkhjw1gVqQyiAYeFyTWKvV2bFUH8HkxrDTYOHRpeaShxrdvWE3K+VmsuEmaXZ+tBUlX6npA+G25eA4rYNeZx9pftoojY3Cwa4LmnOMO5a4JWyw0qUly+CFriqy8WC4FzGWCHQJbhGkYBAtNKU=,iv:THA4/uB82vYEAAwQvNyv0wX088D/KKWesZKW4O4umlQ=,tag:oQKNDtrfSh233NtoSeHuow==,type:str]
    version: 3.13.3
