---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: cairn-web
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: cairn
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        ci: bump cairn-web to {{range .Updated.Images}}{{println .}}{{end}}
    push:
      branch: main
  update:
    path: ./infra/kubernetes/app
    strategy: Setters
