---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./controller/ks.yaml
  - ./applejackrp-sandbox/ks.yaml
  - ./rivet/ks.yaml
  - ./rivet-workstation/ks.yaml
  - ./netpol/ks.yaml
