apiVersion: v1
kind: Secret
metadata:
    name: cluster-backup-restic
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:fcatPA9arjVLCx01cb2mRd6pg1SIMyR7aeqAg2o=,iv:V7VUxgY1q/W8UBNd24MGY6TaJNdoUBnl2nasZ8jKlKU=,tag:72G4+P5rFNFlXoUF6NnZkA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:VNnuPCTdQsqOF8JZnzN2hl7kWfTJtl+5BdxRukKAoQONyfOA4gZM1PbqirY=,iv:3WDl00/1dFEnZOKHJeuiNPMOC6xD2RUd9E4+K1KTs4g=,tag:JY1XGuA0rCvsawh5fN0Tyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRnV2YmxYeXpHdENHelB3
            MXJoRFFmMmV3Y080ZE9aVk1WZGQ5SE5GZURJCklVNFRwU0N3MVREUk9NVjZRL2Zq
            a0JqbWN2M29MNU5KSm8xYVM1Uy9BLzAKLS0tIHloQ3RwOWNpalB2SU8zUzhqRGNq
            QW9uV0lNaHRGQkUrVDlLU1p5UGFrR0kKAJ7xzmooxcC+Jh4AoD3/23OQFUzhrPU3
            UrkdT5WUr/r6QLFsiUPL88zBM7sr4nxR8JZySJsPbGawssQDw5BhnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T14:26:01Z"
    mac: ENC[AES256_GCM,data:n6U3hGnkoXq/mc7gTD9cc+mIsGb4wKINLlG9UvuJC6/dDOQU0bJ2hDvNfabl8KgSJZTQbrdisr/eQIY7FeikmJ18GDWVs3bTakQDakVBJO7VbvS4eiclpD5b8lM2l1wCDvOYGwE/J0q3a4M2LlcUQrpMtIQXM2SXO1ZzXRMkSi4=,iv:qNwUHov5QXmqSFaGTUUnhvEuqm5Lqgj9PV9BOeoiFM0=,tag:8eHrG0eoM29XXCEesxRbjw==,type:str]
    version: 3.13.3
