---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: umami
resources:
  - ./cronjob.yaml
  - ./replicationsource.yaml
  - ./restic-secret.sops.yaml
  - ./volsync-repo-pvc.yaml
  - ./pgdump-pvc.yaml
