apiVersion: v1
kind: Secret
metadata:
    name: umami-pgdump-restic
type: Opaque
data:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ephVZiiufifnOwqSaz5WDg==,iv:KeCxOVCrNdvlLH0cgD0lQjgwIiFC8dfr4cAUxu+pouY=,tag:j8CmJU9+AcsqjslhpSEPTw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:TLKpgyOuUCLk6EmNypSRZoEjBQGqixB9I9TVOIZlyRpWI+q17HAJpA5lD8P5NUfJxspesEBDiuIP+Q5Rtt9XpUaRXr/2AtDyKjx7z9d1AAsO7JwmXeGBng==,iv:hp11LZq4INIP2ukqgqJpHWGS5uyBJ1wrDqYDfW0QAsk=,tag:rplcLGmhiwmB1pBwGahxLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU21SSmRUWXJqckdYMStx
            SUU2L0xaYVgvTm9zSnBQQVNRRmZhdk9jcGp3ClZBb3NpU2FmaWtpMjNRS2Q1dUVO
            MkVJb0lyL0kzNUFFZURQRWVyV3NpNmcKLS0tIHhTR1dzVGYxbGg2VUh6alJLREpC
            a0VRQUdVMFBWNXBFdGRLTHd0WlNzWk0KGeKhIVbg+D805cVT9xUSk8aw8o7lRAXw
            Q3crA831kDooEMNWYL0Wdh/ceT6AN4wJXCltR75spBl4J+gaCxC8Kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T04:22:57Z"
    mac: ENC[AES256_GCM,data:566pG7D7+ODZ2EFEln7CGeQlCmdjsjLQUy+73Ynd2z7YIe1IBI0Z+5AmfgLhuEx9m5U6Z28SXjLyRv/qKIqvwVK0Lruxw0zDTvZ3Tg3b2h1s/qfVYpkQnhyWgiGyKPU0c38UP0F+GP+HehuVuH5YBzosK3YAM4GdYBFldY6tmEI=,iv:fFY5ev0Wa0X/5sdek2mtPShsTmDZvt4NXqWrHYWAAlk=,tag:gJ/NySIxnNqVKD2+A/1Mjw==,type:str]
    version: 3.13.3
