apiVersion: v1
kind: Secret
metadata:
    name: umami-pgdump-restic
type: Opaque
data:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:iGWiARROdo1k7elGYYzqTaZdRtM=,iv:SvCJlbQg5FW6G7csDv/wkVbA3CqQ78yzbouTCLn0w/Q=,tag:4guiZ0lguRgdlqrxXdEIDw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:TLKpgyOuUCLk6EmNypSRZoEjBQGqixB9I9TVOIZlyRpWI+q17HAJpA5lD8P5NUfJxspesEBDiuIP+Q5Rtt9XpUaRXr/2AtDyKjx7z9d1AAsO7JwmXeGBng==,iv:hp11LZq4INIP2ukqgqJpHWGS5uyBJ1wrDqYDfW0QAsk=,tag:rplcLGmhiwmB1pBwGahxLA==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:witeiGWT4K75Bwua69qoVHHGPw3BbVRUNrr/i7JoY40=,iv:NYEaMB7axxHCC2eNISYCx8RxNQ38ioiYGMBjqpKbIv0=,tag:yGQ1Nqur48jnbKN4KCuirw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QbRkk5C2LfLxi5SSZ39pm9DyGFLSJvaiiyV3i80yIryZ1eiM3MW/r7WRUtUSYnBsrQVBozopA08mIrcWAbzw7g==,iv:2yzOYGFaTpsyeI5Ku+tA4qV70ssYLmQVW9IMCgPBXA4=,tag:7tQju0OJkjofZaiyjf+c3g==,type:str]
    AWS_S3_ENDPOINT: ENC[AES256_GCM,data:EQ25zPQT29Dz0qnwqhpZMuKudoqk2anFS4ffk+WQYlThqinkeUEcHVP90HkbbJS0FZpQMxbCh1M70KoO4UaXq6s=,iv:1zDJwYQmgNEjJdRNI02/iSb0VpbQNrUex7izrkP9xPg=,tag:PU+W6h7GnZ5iRDZ2XHor+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU21SSmRUWXJqckdYMStx
            SUU2L0xaYVgvTm9zSnBQQVNRRmZhdk9jcGp3ClZBb3NpU2FmaWtpMjNRS2Q1dUVO
            MkVJb0lyL0kzNUFFZURQRWVyV3NpNmcKLS0tIHhTR1dzVGYxbGg2VUh6alJLREpC
            a0VRQUdVMFBWNXBFdGRLTHd0WlNzWk0KGeKhIVbg+D805cVT9xUSk8aw8o7lRAXw
            Q3crA831kDooEMNWYL0Wdh/ceT6AN4wJXCltR75spBl4J+gaCxC8Kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T11:03:39Z"
    mac: ENC[AES256_GCM,data:HgnugcDI6W8ErP8KODw44vD5q7xNTYYXnWmpcNxbZZebkEQoHjX0S5d0M0LnAKSkquJkfiJAb2G4/eLe0IHHKorqk4rOPC2YHD8NDdbJOy0NlhsgacWNAZXOylpS1SYWQWah7bzodW2J4qbzIhhjzfWiafPSGTjlpEYuvZSXr8c=,iv:qgMLeLDQSkuRGUdirNwDSOqY11F/qnVYoOyFx+aWnPk=,tag:Zb1s2PeE/NtpeDEjSOHTiQ==,type:str]
    version: 3.13.3
