apiVersion: v1
kind: Secret
metadata:
    name: umami-pgdump-restic
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:s8rJEZg4VJrWSA==,iv:BkhmMjnWyWe+g0foJn7vUdmepeLy58jhp9f5Kkeba4U=,tag:J11MOgL24HRJoyg33UyNPA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:MeYN16rfU5dJpKp29pbM1tpT72TAVDzFY2Kcd4x8LgZMa18RXTCYjydCoGC7De+v+sBplTP8Yd8/utJcZPKIHXI=,iv:NShzyjuHDiRxRVodgjoNJzxcYTYjXDfJG9bMwCCEq2Q=,tag:ILF6Mq59nszTP1xEmltxVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU21SSmRUWXJqckdYMStx
            SUU2L0xaYVgvTm9zSnBQQVNRRmZhdk9jcGp3ClZBb3NpU2FmaWtpMjNRS2Q1dUVO
            MkVJb0lyL0kzNUFFZURQRWVyV3NpNmcKLS0tIHhTR1dzVGYxbGg2VUh6alJLREpC
            a0VRQUdVMFBWNXBFdGRLTHd0WlNzWk0KGeKhIVbg+D805cVT9xUSk8aw8o7lRAXw
            Q3crA831kDooEMNWYL0Wdh/ceT6AN4wJXCltR75spBl4J+gaCxC8Kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T04:13:37Z"
    mac: ENC[AES256_GCM,data:r3oNgJA6g6YzaU0MbWflOOMfn1AEUSOFwsE1H/qP0DCFKpQaMuH6E0WcXx6G5y/YVvSu7hxYA+633rhJhNeyiPGuegi1VOTUNWdhOJsGDrBukJpfPRY8D32bw9BSv+l3upiEDu/RSGepGhNstppZwXu0NdbVk88hMisUi+bcz+I=,iv:ZdcnDfGJDsPi4ioTMO80RQW7f17f5K/Ek6UCYGhdKxM=,tag:EXvn3euKy8Ab+osnDJwxeg==,type:str]
    version: 3.13.3
