apiVersion: v1
kind: Secret
metadata:
    name: adguard-credentials
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:WKUJfo9xC2o+qIUEbmwBJGGXZ5Ch8Lk8AA==,iv:9qHf8eLsIB76Nj0GZbkUpfsohMYFwa8EITxhgo724Ng=,tag:PG8phdJNN6L57wtapCnTfA==,type:str]
    user: ENC[AES256_GCM,data:an22CUo=,iv:+2KcrpEQaGh0KPFtImxBWctcGmtyyly+PIJZQYJNVcs=,tag:ELWBf+obtTfnj8IxuORTGQ==,type:str]
    password: ENC[AES256_GCM,data:9Z+5T7y6,iv:15Vz1tQIX6gppyr56xFcJ5TIGdEuIigXBvIf9Z0IuBI=,tag:7h4OsxTzUXNHTfokbA9MLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZk02aWdWeTFLNmxDYU5L
            S2hpdWpud0M0VnRveXQvV1RXYTNURGRTVUJFCmtvQmVBUXluK3hEZnVpNUtFYXZR
            SEd4WU1SUU40QktGNnhYRktRNHNGTEEKLS0tIDNTdWNnQThPejhyMGNxMEdFMFBo
            dVNESkt6RzlLZzJ2bzA2TmorWVRiOVEKeR/mEGLAeW3wjBDRQLVDs43R+pehZfUU
            VPPk9mWCmbdK2yGH/2oL18f+mW3Sk8ZSD/ds4U8WWIovCdMekifi9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T23:40:54Z"
    mac: ENC[AES256_GCM,data:UaB2KVkX90fIncweWBiV1XPK9JKYJmtFE2U6Aug3/dnC6Zq7sD3e4Wmb1KPUIs4rgG/d4jOf/PhGamxA5qGeSx8BIhaVSYpKpjg+BL3e+wfmPAtjahKMp0KrezMACMqLYznJrV9jl2GxhvidCur9klfN5aZcB3Ur7kfuNyESWyU=,iv:gb1Zi5ruemO6/L7THvqdl6qsJfQJBZo95TLtNDaAFZw=,tag:IZSbLKTmreom9+uBTCqfxA==,type:str]
    version: 3.13.3
