apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Bb0G1TIiC81WFbDAetk90d1Y8uRtG5r6Bmwaoj7spvWweFP+udWnN9L7IejbTyRZ8AHvgnL4yIWSk0ax4FcDyos7FzJbZvwa7raICKfJlL2ukdZ8fRJwZvuvKtDdrAfI2WB2ohewbkeyiROVFKKY4Hb8gayrnyIY/YWzBBMb8Clu620xE3GyCSv4TcDcjis2XKJIDSqB4zkejoZ3qIyIlkkp9Gt3eRmBwSWzUFhU5n77EUN82nJ22RBUHP3a37LvnQnG7DZz7pRjTW3MIKuQp6+H0J2HAu+v3kC8c3cAynwFha+E,iv:1q/YNwh0bG7nTZbN+sB4ywQTLngZaXh/Uh5o5hlBfcA=,tag:R7M4Zi1sFZO58qjA3tjzgQ==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: cairn
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eG5BVlhoNVJFKzhQdTcz
            WWFKVVFDR0I4Q2ZaK3hXYldJUmhoY2ZpT1ZJCmZHS3J6VXc1YjJVRWJydWN2Z3E5
            bmtURHhieDMyK1pxMXVWd25HanpmcGcKLS0tIEFPVEdLdHB6SWJPNGpKclhJNDdu
            clNMK2hrOHpybzE5TTBydzB5T3dBRGsKlbdUxt++acYXlM6QxE+Ovry1pizeFuKd
            9J/ts4pY6pNwX5/Tj79tItRAwQ1vjRE0jFDS88jFAqJLGvhMKZMv/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T23:44:41Z"
    mac: ENC[AES256_GCM,data:T5j47nYZhBnfJwuH+sQ0vU8zXx2AdQ4i0N+qBfPuUimMFOQP5WCYHledij8EwtbOZ4XyoVRTkA029A4K+gzB4SgPEdKx0t+H5FX1aDfERXV5mf8IaAczbhE3f2QCRRcRI5fB1i+VTLKZp2r5zwDkgv0RScxf4vrRfVb1caVOhB8=,iv:p81wYBycaYLv7ClWT4vZCwowlLoxpuWu92Y3bHlO0vg=,tag:To+IhVsS2ue+e1ZgY4QzkQ==,type:str]
    version: 3.13.3
