apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:7ZbK5qztgkVcmAQY9MityiYwAV07rMJ7iReACc3Wf/Ede2xUtoUYYRmk4adLfFmDM7Q211pcycnz/vv3xaNwhTaIqUQrRjD8fAtc79TxrAcOk3S3rIxSK5J1HtRUzxF2U4kX2QodP4O+h0oPNBZA03jTs3jdix40rhpPOouu+cIITS3KOx8uT2JBMIfrSV1vc1JBePDM0SUFvyUK7SHaq5Bn6XcuPt2azqbrEhMR71nFwuXK4f23j+NNkEstSTsGonU3DAapczVfgRxkqqTIxA7m8GIL6/7BIaa7HU3cDaYVuhvaoKNy93bAPnofVw+l6X8bDqgRN628fT9NqHStETGSxMXmcQPR,iv:6+897rV4cbJmS/Gl4Pn2C8VOH46LDOHG/lqHpicK6Qo=,tag:XC57NO6KKGNgZHNEAe7xwA==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: applejackrp
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaVlJZVJ5K01OZ2pibTBK
            VVNWQ0R4WXVlUUl4blh0U2IyaGtqdDQ1bkNFCmZ5TkRWNWZGak9YSGs4MnN0eVA0
            NFdrQ0g4U0xZb29UQmwyYVhNbUVMVEUKLS0tIDlQZmNHZUExK2FSejV4WDBTMkor
            QUoxbWVtNDdCT3pqSHpLNWtnZEFQbU0KhgzimZyF4cmMrVDf/rlDbYM5OLmF3ts5
            9TcoadGv8HbJc6+92Z6elYapPk5AM5QQUUg5TdTkdkKXM+jUZUSnfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T17:19:49Z"
    mac: ENC[AES256_GCM,data:m2Edt/MPLslfUTv3ok7cCz7VreCoOhXxVDGb4vmiIu8j+E1IyEdZ0s98BF+CLBmv9exvJFAzSf+vle1XsCizMUUiU+BQGpGlfWTFLftNC/HF0tO0R1koE25My5wc3/M1VE5QyS65KxXXFdebz7llFIwnfRYoGUnzto++BB3M3bI=,iv:OFJ0uFnbw3uoUfPvgUrU5SAaaae2e9yPyxFmc0p8aic=,tag:HgHtgifVDqx0+QhPW6WVTw==,type:str]
    version: 3.13.3
