apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:JB1dvqs2bTNszJhibChT/nyTXJXibIbPfoaV2yhTUCoamw96yWd48FMA8gGCTOr8mm8q57s7G3CMR0KneeWTpgfHMflO+Nsjm5c5TXK93UKxcJKQuCUip3xDwM3DYaFjeI+BIscSYGHxkYOAADiODmWbxRVCX7wK7JOIarORmHl8tOo27azd+yUvUJpbqoOPB8Z5k7riOEb/PoQM++ii7WE73+BfJ1dz5QFEglfxKf/BCsDrYpzkxmejjxMsuWuciqsq4bBLSw7v093RiF1yhv6wQoOqgTj0FHjvWzCFUE1pHU8PsykWXnhPRZ9af+b1VeQWoGE6sZLpFvZhYDlSAdQ4gLyLFQ1V,iv:sK3W3lHU6RihopKKmNHKsz8Bxy/DXLLe2NbGg22ZR3Y=,tag:2XXHsFopYwni7OIOgCjXNA==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: applejackrp
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRXdzMmI4SGJKRzNBWS9C
            bVBMS2NvcTVHcVJkRlg3dzZLRUQ5Y2pmeHpVCmJScDhxT3BaaE05c0taVWtOTTRL
            ZTZWTC8xNVkySmFPRnFMNzVJWjlyMFUKLS0tIHh5OXgzQ0tYTHdEOGVNQ0d3TW1i
            VnJRVG9pUVZNc0p2TnEyUmoxbzBVNzQKXvrmFwvmxkl2TrLkHREkkmBvooNkommd
            prMCG97kx7q3sde9vRIAVvEBpFuIY2cwoRbCtJz/VQUuGbTAHUipmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T17:44:39Z"
    mac: ENC[AES256_GCM,data:Hncy7520OsOSwp3/REgzvjlIvCYhPNkfUfHChOrxZlgVTaANwq3Kjx5NufexJXym85a5ut++vLEtvYBRs8e+3hmpXr90fN7Vwx+L7+Cvk3aqWe2MDlZGnc5aqPhA25G7ZNI0ZnibdgEdAb4fDdTRzjZKhhN+vmHMd0gGbKk6vaI=,iv:L0g01iwAtljy92zBQVqHUlxXYIsXG8/uBHWxIFEUBvU=,tag:MSVbptCJVolRYxqWneZXeA==,type:str]
    version: 3.13.3
