apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:XCKvUIJQxbWIV3fBDPSazqq0oOF+EntOH13myu2JGSk32V5jxV+5W4AuHyuNAf5VM4MVytfIoLUej65S9ZTxyRu9YclRh4wG41AUEjHpivWJJozzDEwJnIUpBMwmshHd2+cDgn5BK33MIf0v2y7xZsmfsBrn6xqLSlLgRhtmuF6pRj188ZG9fRlL6hU+cE2cb+v3j50Y3zjlM5xgjyCN5JJaohcHg2uHQ9P9nHzhbo52xaQfHoSY22IaqFSfKt29tJF4wAjFNpK4fNxJwKL5DsHtBbQGeok/Gqn9iR2bvCy8/AJxJtidIHh4jomo8QSV/DVA54t/zQbAao6TKZ0SVCRyFl+F6T3xNyC9Tr26bbVbs+X/wrxFsDv9B63kBpFpVMMtxLFFftFD5aZW09hQGf9fFneC27dUds9jPyvYN1ShnYMdurH5YWVRekDFeeayTV0YLOQ+7PE93gZNn1egCyCyajIGF4301wuWYuANxXlw4+Mn3DsUqrJo00ttV0IbRS2MqTC7gfxkfCAo5MxfI08d9vRpX35m6bdv4JPrvDrGOQ6P62vZ/hI23EO5nFSS,iv:WakiG8KCX+mmcL+bVaG1hTTZtvk9LrzHerJ8qFpiVH4=,tag:FStK39Bzri/x3QwfyC1wsQ==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: applejackrp
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSysyZzBGclNVZ1cvZG8w
            dC91K2hrell1V3ZzNC9sdkt1RkVRamtDMFJzCnF6U1lRQ3VhckZFbFFWUE1WNXdT
            dWRqd2dnc0ExR3RmZzQwazh3dk1XNk0KLS0tIEw2VmxlM2NKQzJGUlE1OW5lWGZy
            Mk1KVFUrT2Iza0liWWlQWVFPSXQ5Q2sK095vgLpTxPphw+00Ad1e9iaz2Lj7UTgX
            //KOP1kLkCbKj3VR4iqApcWNWpwDmKP1feKK4Mi1/RgcukBcKF5bKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p8gv792c4npw2xt3pq8yhu23u47v2sprdatceq779r34nzp24pqrd92vg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T16:39:26Z"
    mac: ENC[AES256_GCM,data:KjOSbDavHywZJrjmQaLXiYy9Pc1ZA93EjWJLtEmuB6VTwdOsxrx1o1D9kStiPsLkUZnFeexTuoL7Uh3tp4OlmPR9xUPlj7dMX5k/zQdPdwNFOcTwLZv3hiKKBK2E9zYfleHfJgUfZOwnO7EexCKBM+Di74eOtg3AC9ODNjuMZfE=,iv:LzuB8QBwWx5J4IxC9fj/jAqSBhQlv0LAaKWT0RV+adY=,tag:PbzB0WoVtBtlxZ+yMr52Jw==,type:str]
    version: 3.13.3
